version: '3'
services:
  mysql:
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/mysql-dbaccess.cnf:/root/mysql-dbaccess.cnf
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined
